### ISSUE TITLE
Merge bin/mycha and mycha.bin

### ISSUE THREAD

**Issue by kevgo** [Originate/mycha#18]
These two things seem to do the same things, make Mycha available on the command line. Any reasons that speak against this?

**Comment by charlierudolph** [comment]
@kevgo can you please reevaluate this issue and what you would like to happen. Many things have changed since this was opened.

**Comment by kevgo** [comment]
I'm not feeling strongly about this, and mycha.bin seems gone, so feel free to close this at your own digression.
