### ISSUE TITLE
Full support for "spec" folder

### ISSUE THREAD

**Issue by kevgo** [Originate/mycha#30]
Specs should be in the spec folder. Even though the NPM convention is "test", this is wrong and misleading. Mycha should find specs in the "spec" folder similar to how it should find tests in the "test" folder, and run both.

**Comment by charlierudolph** [comment]
@kevgo can this be closed? I believe it is irrelevant now

**Comment by kevgo** [comment]
I don't think this is ever going to be irrelevant, since we definitely should support both `spec` and `test` folders even in the new implementation. If this works now, though, feel free to close this ticket  :)

**Comment by charlierudolph** [comment]
I meant its irrelevant because mycha no longer has a default folder that it expects tests to live in.
Instead it now find tests anywhere in the project. Thus closing as its now fixed.
