### ISSUE TITLE
Use JS API of Mocha

### ISSUE THREAD

**Issue by kevgo** [Originate/mycha#31]
https://github.com/sindresorhus/gulp-mocha/blob/master/index.js

This file demonstrates how to use the JS API of Mocha's NPM module. We should do something similar in Mycha. This should greatly simplify things.

**Comment by charlierudolph** [comment]
@kevgo we discussed that this wasn't possible in my PR (because we would have to do mocha's command line parsing). Can this be closed?

**Comment by kevgo** [comment]
Yeah, this is old. Closing.
