### ISSUE TITLE
Use YML for configuration file

### ISSUE THREAD

**Issue by kevgo** [Originate/mycha#63]
@alexdavid suggested that YML is a good superset of JSON. I agree. Looking at the current config file format for Mycha, I don't see a strong reason to stick with coffee script. What do we think about using YML here @charlierudolph @alexdavid?

**Comment by alexdavid** [comment]
:+1:

**Comment by charlierudolph** [comment]
:+1:

**Comment by alexdavid** [comment]
If we're going to use .yml what do you think about calling it just `mycha.yml` (instead of `mycha_config.yml` proposed in #58).

I think the yaml extension is pretty self explanatory that we're dealing with a config and not code.

**Comment by kevgo** [comment]
I have closed #58 in favor of this solution.
