### ISSUE TITLE
LiveScript support

### ISSUE THREAD

**Issue by kevgo** [Originate/mycha#69]
LiveScript is a more actively developed CoffeeScript-like language that includes pragmatic, dynamically-typed functional concepts (without becoming academic), as well as better ES6 compatibility. Overall it seems like the CoffeeScript idea thought all the way to the end. Mycha should support it.

* determine if LiveScript or CoffeeScript is used by inspecting the local `package.json` file
* generate a `mycha.ls` file instead of `mycha.coffee` and use it when it exists
* add `'ls:livescript'` to the `compilers` section
* add `.ls` to the testFilePattern section
* in the LiveScript files, make camelCased identifiers spinal-cased

**Comment by alexdavid** [comment]
LiveScript doesn't work with Mocha because `it` is a reserved word in LiveScript, and Mocha uses `it` for test blocks.

**Comment by alexdavid** [comment]
I suppose we could globally alias `global.It = it` or something for LiveScript since it only breaks when used in a function

**Comment by kevgo** [comment]
An easy workaround for this is to provide a parameter to the "describe" callback. This could be an underscore (indicating an unused parameter) or a splat. An example is given at https://github.com/Originate/new-technology-playground/blob/master/livescript/fizzbuzz/fizzbuzz_spec.ls

Clearly not ideal, but the benefits of LiveScript far outweigh this disadvantage imho.

**Comment by alexdavid** [comment]
Apparently mocha already aliases it to `specify`. So I suppose livescript users can use `specify` instead of `it`

**Comment by kevgo** [comment]
Ah, that's another cool trick, thanks!

**Comment by charlierudolph** [comment]
How about joining this with #63? That way we only have one language specific file which is the test helper.  Would be cool to also have the installer pick the language (and have the defaulted value be smart based on idea about searching the package.json). I think it would be awesome to also have mycha for js projects, so I'd like to add default js support and then make it easy for us to add new languages.
